using System.Runtime.CompilerServices;
[assembly: InternalsVisibleTo("Test.Shared.Core")]
[assembly: InternalsVisibleTo("Test.TestingUtility")]
[assembly: InternalsVisibleTo("Test.GameWorld.Core")]
[assembly: InternalsVisibleTo("GameWorld.CoreTest")]
[assembly: InternalsVisibleTo("Shared.CoreTest")]
[assembly: InternalsVisibleTo("Shared.UiTest")]
[assembly: InternalsVisibleTo("Test.ImportExport")]
[assembly: InternalsVisibleTo("Test.AnimatioReTarget")]
