namespace Shared.GameFormats.Wwise.Enums
{
    public enum AkPropId_V136 : byte
    {
        Volume = 0x00,
        LFE = 0x01,
        Pitch = 0x02,
        LPF = 0x03,
        HPF = 0x04,
        BusVolume = 0x05,
        MakeUpGain = 0x06,
        Priority = 0x07,
        PriorityDistanceOffset = 0x08,
        MuteRatio = 0x0B,
        PAN_LR = 0x0C,
        PAN_FR = 0x0D,
        CenterPCT = 0x0E,
        DelayTime = 0x0F,
        TransitionTime = 0x10,
        Probability = 0x11,
        DialogueMode = 0x12,
        UserAuxSendVolume0 = 0x13,
        UserAuxSendVolume1 = 0x14,
        UserAuxSendVolume2 = 0x15,
        UserAuxSendVolume3 = 0x16,
        GameAuxSendVolume = 0x17,
        OutputBusVolume = 0x18,
        OutputBusHPF = 0x19,
        OutputBusLPF = 0x1A,
        HDRBusThreshold = 0x1B,
        HDRBusRatio = 0x1C,
        HDRBusReleaseTime = 0x1D,
        HDRBusGameParam = 0x1E,
        HDRBusGameParamMin = 0x1F,
        HDRBusGameParamMax = 0x20,
        HDRActiveRange = 0x21,
        LoopStart = 0x22,
        LoopEnd = 0x23,
        TrimInTime = 0x24,
        TrimOutTime = 0x25,
        FadeInTime = 0x26,
        FadeOutTime = 0x27,
        FadeInCurve = 0x28,
        FadeOutCurve = 0x29,
        LoopCrossfadeDuration = 0x2A,
        CrossfadeUpCurve = 0x2B,
        CrossfadeDownCurve = 0x2C,
        MidiTrackingRootNote = 0x2D,
        MidiPlayOnNoteType = 0x2E,
        MidiTransposition = 0x2F,
        MidiVelocityOffset = 0x30,
        MidiKeyRangeMin = 0x31,
        MidiKeyRangeMax = 0x32,
        MidiVelocityRangeMin = 0x33,
        MidiVelocityRangeMax = 0x34,
        MidiChannelMask = 0x35,
        PlaybackSpeed = 0x36,
        MidiTempoSource = 0x37,
        MidiTargetNode = 0x38,
        AttachedPluginFXID = 0x39,
        Loop = 0x3A,
        InitialDelay = 0x3B,
        UserAuxSendLPF0 = 0x3C,
        UserAuxSendLPF1 = 0x3D,
        UserAuxSendLPF2 = 0x3E,
        UserAuxSendLPF3 = 0x3F,
        UserAuxSendHPF0 = 0x40,
        UserAuxSendHPF1 = 0x41,
        UserAuxSendHPF2 = 0x42,
        UserAuxSendHPF3 = 0x43,
        GameAuxSendLPF = 0x44,
        GameAuxSendHPF = 0x45,
        AttenuationID = 0x46,
        PositioningTypeBlend = 0x47,
        ReflectionBusVolume = 0x48
    }

    public enum AkPluginType_V136 : ushort
    {
        None = 0x00,
        Codec = 0x01,
        Source = 0x02,
        Effect = 0x03,
        MotionDevice = 0x04,
        MotionSource = 0x05,
        Mixer = 0x06,
        Sink = 0x07,
        GlobalExtension = 0x08
    }
}
