name: Run-Unit-Test

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-and-test:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build AssetEditor\AssetEditor.csproj --no-restore

    - name: Run Shared.Core Tests
      run: dotnet test Testing\Shared.Core.Test\Test.Shared.Core.csproj --no-restore --verbosity normal

    - name: Run GameWorld.Core Tests
      run: dotnet test Testing\GameWorld.Core.Test\Test.GameWorld.Core.csproj --no-restore --verbosity normal

    - name: Run E2E Verification Tests
      run: dotnet test Testing\E2EVerification\Test.E2EVerification.csproj --no-restore --verbosity normal

    - name: Run Editors.ImportExport Tests
      run: dotnet test Editors\ImportExportEditor\Test.ImportExport\Test.ImportExport.csproj --no-restore --verbosity normal

    - name: Run Editors.SkeletonEditor Tests
      run: dotnet test Editors\SkeletonEditor\Test.SkeletonEditor\Test.SkeletonEditor.csproj --no-restore --verbosity normal

    - name: Run Editors.AnimatioReTarget Tests
      run: dotnet test Editors\AnimationReTarget\Test.AnimatioReTarget\Test.AnimatioReTarget.csproj --no-restore --verbosity normal

    - name: Run Editors.Kitbashing Tests
      run: dotnet test Editors\Kitbashing\Test.KitbashEditor\Test.KitbashEditor.csproj --no-restore --verbosity normal